### ISSUE TITLE
Plugin fails to unload every second load

### ISSUE THREAD

**Issue by moremeyou** [pjeby/hot-reload#13]
Hi there,
This issues just started happening. Can't be sure if I've caused it. But maybe you can help.

Plugin failure: tag-buddy TypeError: Cannot read properties of undefined (reading 'e')
    at app.js:1:1148287
    at e.unload (app.js:1:1147899)
    at e.<anonymous> (app.js:1:2027133)
    at app.js:1:237258
    at Object.next (app.js:1:237363)
    at app.js:1:236279
    at new Promise (<anonymous>)
    at v (app.js:1:236024)
    at e.unloadPlugin (app.js:1:2027038)
    at e.<anonymous> (app.js:1:2030070)
    at app.js:1:237258
    at Object.next (app.js:1:237363)
    at app.js:1:236279
    at new Promise (<anonymous>)
    at v (app.js:1:236024)
    at e.disablePlugin (app.js:1:2029944)
    at HotReload.reload (plugin:hot-reload:95:23)
    at eval (plugin:hot-reload:84:79)

**Comment by pjeby** [comment]
Does the same error occur when you manually disable the plugin?

**Comment by moremeyou** [comment]
It does! Sorry to bother you with it.
I'll work it out :)
D
